service: anirakservice

useDotenv: true
variablesResolutionMode: 20210219

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ${env:REGION}
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::anirak/*"

functions:
  createTask:
    handler: handlers/tasks.createTask
    events:
      - http:
          path: /api/v1/task
          method: post
          cors: true
  editTask:
    handler: handlers/tasks.editTask
    events:
      - http:
          path: /api/v1/task/{id}
          method: put
          cors: true
  getTasks:
    handler: handlers/tasks.getTasks
    events:
      - http:
          path: /api/v1/task
          method: get
          cors: true
  deleteTask:
    handler: handlers/tasks.deleteTask
    events:
      - http:
          path: /api/v1/task/{id}
          method: delete
          cors: true
  getSongs:
    handler: handler.getSongs
    events:
      - http:
          path: /api/v1/song
          method: get
          cors: true
  getMonths:
    handler: handlers/months.getMonths
    events:
      - http:
          path: /api/v1/month
          method: get
          cors: true
  addMonth:
    handler: handlers/months.addMonth
    events:
      - http:
          path: /api/v1/month
          method: post
          cors: true
  uploadFile:
    handler: handlers/upload-file.main
    events:
      - http:
          path: /api/v1/file
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
